# CQAR Development Configuration
# Overrides base config for local development

service:
  env: "development"

server:
  grpc_port: 9090
  http_port: 8080

database:
  host: "localhost"
  port: 5432
  user: "cqar"
  password: "cqar_dev_password"
  database: "cqar"
  ssl_mode: "disable"

cache:
  host: "localhost"
  port: 6379
  password: "cqar_dev_password"

eventbus:
  backend: "jetstream"
  servers:
    - "nats://localhost:4222"
  stream_name: "cqc_events"

log:
  level: "debug"
  format: "console"

tracing:
  enabled: true
  endpoint: "localhost:4317"
  sample_rate: 1.0  # Sample all traces in development

auth:
  api_keys:
    - "dev_key_cqmd_12345"
    - "dev_key_cqpm_67890"
    - "dev_key_cqvx_abcde"
    - "dev_key_test_99999"  # Extra key for testing
