# CQAR Base Configuration
# Extends CQI base configuration structure

service:
  name: "cqar"
  version: "0.1.0"
  env: "development"

server:
  http_port: 8080
  grpc_port: 9090
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "30s"

database:
  host: "localhost"
  port: 5432
  user: "cqar"
  password: "cqar_dev_password"
  database: "cqar"
  ssl_mode: "disable"
  max_conns: 25
  min_conns: 5
  max_conn_lifetime: "15m"
  max_conn_idle_time: "5m"
  connect_timeout: "5s"
  query_timeout: "30s"

cache:
  host: "localhost"
  port: 6379
  password: "cqar_dev_password"
  db: 0
  default_ttl: "60m"
  max_retries: 3
  min_idle_conns: 5
  pool_size: 10

eventbus:
  backend: "jetstream"
  servers:
    - "nats://localhost:4222"
  stream_name: "cqc_events"
  consumer_name: "cqar"
  max_deliver: 3
  ack_wait: "30s"
  max_ack_pending: 1000

log:
  level: "info"
  format: "json"
  output: "stdout"

metrics:
  enabled: true
  port: 9091
  path: "/metrics"
  namespace: "cqar"

tracing:
  enabled: false
  endpoint: ""
  sample_rate: 0.1
  service_name: "cqar"

auth:
  api_keys:
    - "dev_key_cqmd_12345"
    - "dev_key_cqpm_67890"
    - "dev_key_cqvx_abcde"

# CQAR-specific settings
cache_ttl:
  asset: "60m"
  symbol: "60m"
  venue: "60m"
  venue_asset: "15m"
  venue_symbol: "15m"
  quality_flag: "5m"
