apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cqar-logs
  namespace: cqar
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
